// Generated by CoffeeScript 1.7.1
(function() {
  [new Card('h', 5), new Card('s', 5), new Card('c', 5)].reduce(function(x, y) {
    return x.val + y.val;
  });

  alert(["o", "oo"].reduce(function(x, y) {
    return x.length + y.length;
  }));

}).call(this);
